//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/Scripts/Input/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Input/PlayerActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""PlayerActs"",
            ""id"": ""88a6c140-4e7b-48c3-9445-8292a021e93e"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""c7aefc61-513a-473f-8e86-579d72e0d5e3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Command"",
                    ""type"": ""Button"",
                    ""id"": ""20527fb6-4933-41a6-b51b-b8e6f89ddf8e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ModifierShift"",
                    ""type"": ""Button"",
                    ""id"": ""e26ed319-3b2b-4048-9e7d-84aba6e2b1bf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ModifierControl"",
                    ""type"": ""Button"",
                    ""id"": ""08638ea7-5ed4-41c2-8b9c-5a360ebb3948"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""2de3dd1d-df42-4ef1-b75a-ef31d9411cc7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NumberKey1"",
                    ""type"": ""Button"",
                    ""id"": ""b9fcb022-3b48-4f0a-837e-e4083178c79c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey2"",
                    ""type"": ""Button"",
                    ""id"": ""cdf240a8-6f74-4244-aaf5-46fbc5fa9ad1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey3"",
                    ""type"": ""Button"",
                    ""id"": ""57abb3e6-3dc0-432a-a8c9-60008390ac71"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey4"",
                    ""type"": ""Button"",
                    ""id"": ""508e1d77-6161-47de-b0eb-c2e1ca305d1b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey5"",
                    ""type"": ""Button"",
                    ""id"": ""ac84aaa1-09f6-4a57-8312-b6383e7c8e0a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey6"",
                    ""type"": ""Button"",
                    ""id"": ""0ee5416f-a9b3-43db-8c23-6a51417af891"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey7"",
                    ""type"": ""Button"",
                    ""id"": ""2df42c3c-33ab-4956-9f7a-c2ef6ce787d7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey8"",
                    ""type"": ""Button"",
                    ""id"": ""0c43d059-545a-42fd-b148-46dca331f19e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey9"",
                    ""type"": ""Button"",
                    ""id"": ""5fbec25e-c685-4ba0-aebb-aa3adf153c51"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMove"",
                    ""type"": ""Value"",
                    ""id"": ""3473c88e-ea89-431e-b110-e0d692dd5e4a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraRotateToggle"",
                    ""type"": ""Value"",
                    ""id"": ""21a8a398-329e-49e3-ae88-127566977631"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToggleOverviewZoom"",
                    ""type"": ""Button"",
                    ""id"": ""681524e9-4b8c-47b3-a6c2-7a05c4ce9d29"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CenterOnSelection"",
                    ""type"": ""Button"",
                    ""id"": ""9f91debc-157c-4a30-b160-49d81f131a9f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleFollowSelection"",
                    ""type"": ""Button"",
                    ""id"": ""3337d44d-4b1e-4146-a0dc-5712412b2460"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GoHome"",
                    ""type"": ""Button"",
                    ""id"": ""b2312b98-e82f-4b84-ba20-21fda0880322"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraZoomScroll"",
                    ""type"": ""Value"",
                    ""id"": ""62a38dad-6e55-4537-9a29-131faf9b1ba8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Spawn"",
                    ""type"": ""Button"",
                    ""id"": ""8ffbc9e6-54b0-43f9-9230-8c2b82876a66"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Despawn"",
                    ""type"": ""Button"",
                    ""id"": ""ecb7f272-f7f9-4faa-a2c3-527d50df9ee2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""34bfbd39-31cb-498d-bdd6-d6cd6772a724"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9de59ce-c67d-498e-95a1-88702eb00ccf"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Command"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf547a5f-20c4-4f52-9f31-5a78cc3bada4"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ModifierShift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e5eb7b3-5a79-4374-a790-d39aae89c56c"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ModifierControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""1fe94158-eceb-43fe-b2a0-f1bc94a26f48"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""9b5c15c9-3012-490e-a1ab-0f2a9ef4238d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""67b6c7df-3a57-4551-8947-ee2632ad1cb0"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""bb1519c5-3dc4-4dfa-8752-5af9da5ee593"",
                    ""path"": ""OneModifier"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateToggle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8409e941-71ed-416c-ad3f-7c0417521ca3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""8d1c78bb-1b3b-4db0-9fb5-7156ea3655da"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c768fe33-ac89-45d7-b888-a026b182d29a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberKey1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7cda5a3-74d2-4855-b4a1-dd13bad32844"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberKey2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ac0854a-d7a0-4d34-b180-f1b5eb9c8400"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberKey3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba42bd9b-d37b-4a0d-ba89-dc1bbfda810c"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberKey4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90614d08-ad41-485c-a3e5-f5d3fada4acc"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberKey5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caa3407a-b542-4279-beab-3789c68b605d"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberKey6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b4df37c-12fa-457f-9b03-f05b0b80710b"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberKey7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f253d78-0f19-4a2b-8345-2fc3596b2746"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberKey8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06c5cf76-77de-4377-8a7a-412063d1f04d"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberKey9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ccfc8b0-43a8-44c8-a4fd-329d83d007ea"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleOverviewZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13b7b00d-c4f7-4d20-bbb1-83d8363ee9b1"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CenterOnSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""4b111866-8fa6-4f15-88e1-4378b69ae542"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleFollowSelection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""48bd6f9e-6679-4ce8-8460-cc9da479e04f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleFollowSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""89c1e1ed-97af-477f-be95-172256cccc9f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleFollowSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""93eeb204-5ca5-4bef-8342-26904a55e622"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e88dc881-76c0-49ac-9b37-a09374777bcb"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoHome"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ed94656-48c9-4540-84c0-b3024ede6387"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoomScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23ed3c2a-f594-403e-8431-afe2d46f1c74"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97df829c-78a0-46bf-abdf-1d35a1f31919"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Despawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerActs
        m_PlayerActs = asset.FindActionMap("PlayerActs", throwIfNotFound: true);
        m_PlayerActs_Select = m_PlayerActs.FindAction("Select", throwIfNotFound: true);
        m_PlayerActs_Command = m_PlayerActs.FindAction("Command", throwIfNotFound: true);
        m_PlayerActs_ModifierShift = m_PlayerActs.FindAction("ModifierShift", throwIfNotFound: true);
        m_PlayerActs_ModifierControl = m_PlayerActs.FindAction("ModifierControl", throwIfNotFound: true);
        m_PlayerActs_MousePosition = m_PlayerActs.FindAction("MousePosition", throwIfNotFound: true);
        m_PlayerActs_NumberKey1 = m_PlayerActs.FindAction("NumberKey1", throwIfNotFound: true);
        m_PlayerActs_NumberKey2 = m_PlayerActs.FindAction("NumberKey2", throwIfNotFound: true);
        m_PlayerActs_NumberKey3 = m_PlayerActs.FindAction("NumberKey3", throwIfNotFound: true);
        m_PlayerActs_NumberKey4 = m_PlayerActs.FindAction("NumberKey4", throwIfNotFound: true);
        m_PlayerActs_NumberKey5 = m_PlayerActs.FindAction("NumberKey5", throwIfNotFound: true);
        m_PlayerActs_NumberKey6 = m_PlayerActs.FindAction("NumberKey6", throwIfNotFound: true);
        m_PlayerActs_NumberKey7 = m_PlayerActs.FindAction("NumberKey7", throwIfNotFound: true);
        m_PlayerActs_NumberKey8 = m_PlayerActs.FindAction("NumberKey8", throwIfNotFound: true);
        m_PlayerActs_NumberKey9 = m_PlayerActs.FindAction("NumberKey9", throwIfNotFound: true);
        m_PlayerActs_CameraMove = m_PlayerActs.FindAction("CameraMove", throwIfNotFound: true);
        m_PlayerActs_CameraRotateToggle = m_PlayerActs.FindAction("CameraRotateToggle", throwIfNotFound: true);
        m_PlayerActs_ToggleOverviewZoom = m_PlayerActs.FindAction("ToggleOverviewZoom", throwIfNotFound: true);
        m_PlayerActs_CenterOnSelection = m_PlayerActs.FindAction("CenterOnSelection", throwIfNotFound: true);
        m_PlayerActs_ToggleFollowSelection = m_PlayerActs.FindAction("ToggleFollowSelection", throwIfNotFound: true);
        m_PlayerActs_GoHome = m_PlayerActs.FindAction("GoHome", throwIfNotFound: true);
        m_PlayerActs_CameraZoomScroll = m_PlayerActs.FindAction("CameraZoomScroll", throwIfNotFound: true);
        m_PlayerActs_Spawn = m_PlayerActs.FindAction("Spawn", throwIfNotFound: true);
        m_PlayerActs_Despawn = m_PlayerActs.FindAction("Despawn", throwIfNotFound: true);
    }

    ~@PlayerActions()
    {
        UnityEngine.Debug.Assert(!m_PlayerActs.enabled, "This will cause a leak and performance issues, PlayerActions.PlayerActs.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerActs
    private readonly InputActionMap m_PlayerActs;
    private List<IPlayerActsActions> m_PlayerActsActionsCallbackInterfaces = new List<IPlayerActsActions>();
    private readonly InputAction m_PlayerActs_Select;
    private readonly InputAction m_PlayerActs_Command;
    private readonly InputAction m_PlayerActs_ModifierShift;
    private readonly InputAction m_PlayerActs_ModifierControl;
    private readonly InputAction m_PlayerActs_MousePosition;
    private readonly InputAction m_PlayerActs_NumberKey1;
    private readonly InputAction m_PlayerActs_NumberKey2;
    private readonly InputAction m_PlayerActs_NumberKey3;
    private readonly InputAction m_PlayerActs_NumberKey4;
    private readonly InputAction m_PlayerActs_NumberKey5;
    private readonly InputAction m_PlayerActs_NumberKey6;
    private readonly InputAction m_PlayerActs_NumberKey7;
    private readonly InputAction m_PlayerActs_NumberKey8;
    private readonly InputAction m_PlayerActs_NumberKey9;
    private readonly InputAction m_PlayerActs_CameraMove;
    private readonly InputAction m_PlayerActs_CameraRotateToggle;
    private readonly InputAction m_PlayerActs_ToggleOverviewZoom;
    private readonly InputAction m_PlayerActs_CenterOnSelection;
    private readonly InputAction m_PlayerActs_ToggleFollowSelection;
    private readonly InputAction m_PlayerActs_GoHome;
    private readonly InputAction m_PlayerActs_CameraZoomScroll;
    private readonly InputAction m_PlayerActs_Spawn;
    private readonly InputAction m_PlayerActs_Despawn;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerActs".
    /// </summary>
    public struct PlayerActsActions
    {
        private @PlayerActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerActsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/Select".
        /// </summary>
        public InputAction @Select => m_Wrapper.m_PlayerActs_Select;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/Command".
        /// </summary>
        public InputAction @Command => m_Wrapper.m_PlayerActs_Command;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/ModifierShift".
        /// </summary>
        public InputAction @ModifierShift => m_Wrapper.m_PlayerActs_ModifierShift;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/ModifierControl".
        /// </summary>
        public InputAction @ModifierControl => m_Wrapper.m_PlayerActs_ModifierControl;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/MousePosition".
        /// </summary>
        public InputAction @MousePosition => m_Wrapper.m_PlayerActs_MousePosition;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/NumberKey1".
        /// </summary>
        public InputAction @NumberKey1 => m_Wrapper.m_PlayerActs_NumberKey1;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/NumberKey2".
        /// </summary>
        public InputAction @NumberKey2 => m_Wrapper.m_PlayerActs_NumberKey2;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/NumberKey3".
        /// </summary>
        public InputAction @NumberKey3 => m_Wrapper.m_PlayerActs_NumberKey3;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/NumberKey4".
        /// </summary>
        public InputAction @NumberKey4 => m_Wrapper.m_PlayerActs_NumberKey4;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/NumberKey5".
        /// </summary>
        public InputAction @NumberKey5 => m_Wrapper.m_PlayerActs_NumberKey5;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/NumberKey6".
        /// </summary>
        public InputAction @NumberKey6 => m_Wrapper.m_PlayerActs_NumberKey6;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/NumberKey7".
        /// </summary>
        public InputAction @NumberKey7 => m_Wrapper.m_PlayerActs_NumberKey7;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/NumberKey8".
        /// </summary>
        public InputAction @NumberKey8 => m_Wrapper.m_PlayerActs_NumberKey8;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/NumberKey9".
        /// </summary>
        public InputAction @NumberKey9 => m_Wrapper.m_PlayerActs_NumberKey9;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/CameraMove".
        /// </summary>
        public InputAction @CameraMove => m_Wrapper.m_PlayerActs_CameraMove;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/CameraRotateToggle".
        /// </summary>
        public InputAction @CameraRotateToggle => m_Wrapper.m_PlayerActs_CameraRotateToggle;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/ToggleOverviewZoom".
        /// </summary>
        public InputAction @ToggleOverviewZoom => m_Wrapper.m_PlayerActs_ToggleOverviewZoom;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/CenterOnSelection".
        /// </summary>
        public InputAction @CenterOnSelection => m_Wrapper.m_PlayerActs_CenterOnSelection;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/ToggleFollowSelection".
        /// </summary>
        public InputAction @ToggleFollowSelection => m_Wrapper.m_PlayerActs_ToggleFollowSelection;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/GoHome".
        /// </summary>
        public InputAction @GoHome => m_Wrapper.m_PlayerActs_GoHome;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/CameraZoomScroll".
        /// </summary>
        public InputAction @CameraZoomScroll => m_Wrapper.m_PlayerActs_CameraZoomScroll;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/Spawn".
        /// </summary>
        public InputAction @Spawn => m_Wrapper.m_PlayerActs_Spawn;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActs/Despawn".
        /// </summary>
        public InputAction @Despawn => m_Wrapper.m_PlayerActs_Despawn;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerActs; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerActsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerActsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerActsActions" />
        public void AddCallbacks(IPlayerActsActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActsActionsCallbackInterfaces.Add(instance);
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Command.started += instance.OnCommand;
            @Command.performed += instance.OnCommand;
            @Command.canceled += instance.OnCommand;
            @ModifierShift.started += instance.OnModifierShift;
            @ModifierShift.performed += instance.OnModifierShift;
            @ModifierShift.canceled += instance.OnModifierShift;
            @ModifierControl.started += instance.OnModifierControl;
            @ModifierControl.performed += instance.OnModifierControl;
            @ModifierControl.canceled += instance.OnModifierControl;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @NumberKey1.started += instance.OnNumberKey1;
            @NumberKey1.performed += instance.OnNumberKey1;
            @NumberKey1.canceled += instance.OnNumberKey1;
            @NumberKey2.started += instance.OnNumberKey2;
            @NumberKey2.performed += instance.OnNumberKey2;
            @NumberKey2.canceled += instance.OnNumberKey2;
            @NumberKey3.started += instance.OnNumberKey3;
            @NumberKey3.performed += instance.OnNumberKey3;
            @NumberKey3.canceled += instance.OnNumberKey3;
            @NumberKey4.started += instance.OnNumberKey4;
            @NumberKey4.performed += instance.OnNumberKey4;
            @NumberKey4.canceled += instance.OnNumberKey4;
            @NumberKey5.started += instance.OnNumberKey5;
            @NumberKey5.performed += instance.OnNumberKey5;
            @NumberKey5.canceled += instance.OnNumberKey5;
            @NumberKey6.started += instance.OnNumberKey6;
            @NumberKey6.performed += instance.OnNumberKey6;
            @NumberKey6.canceled += instance.OnNumberKey6;
            @NumberKey7.started += instance.OnNumberKey7;
            @NumberKey7.performed += instance.OnNumberKey7;
            @NumberKey7.canceled += instance.OnNumberKey7;
            @NumberKey8.started += instance.OnNumberKey8;
            @NumberKey8.performed += instance.OnNumberKey8;
            @NumberKey8.canceled += instance.OnNumberKey8;
            @NumberKey9.started += instance.OnNumberKey9;
            @NumberKey9.performed += instance.OnNumberKey9;
            @NumberKey9.canceled += instance.OnNumberKey9;
            @CameraMove.started += instance.OnCameraMove;
            @CameraMove.performed += instance.OnCameraMove;
            @CameraMove.canceled += instance.OnCameraMove;
            @CameraRotateToggle.started += instance.OnCameraRotateToggle;
            @CameraRotateToggle.performed += instance.OnCameraRotateToggle;
            @CameraRotateToggle.canceled += instance.OnCameraRotateToggle;
            @ToggleOverviewZoom.started += instance.OnToggleOverviewZoom;
            @ToggleOverviewZoom.performed += instance.OnToggleOverviewZoom;
            @ToggleOverviewZoom.canceled += instance.OnToggleOverviewZoom;
            @CenterOnSelection.started += instance.OnCenterOnSelection;
            @CenterOnSelection.performed += instance.OnCenterOnSelection;
            @CenterOnSelection.canceled += instance.OnCenterOnSelection;
            @ToggleFollowSelection.started += instance.OnToggleFollowSelection;
            @ToggleFollowSelection.performed += instance.OnToggleFollowSelection;
            @ToggleFollowSelection.canceled += instance.OnToggleFollowSelection;
            @GoHome.started += instance.OnGoHome;
            @GoHome.performed += instance.OnGoHome;
            @GoHome.canceled += instance.OnGoHome;
            @CameraZoomScroll.started += instance.OnCameraZoomScroll;
            @CameraZoomScroll.performed += instance.OnCameraZoomScroll;
            @CameraZoomScroll.canceled += instance.OnCameraZoomScroll;
            @Spawn.started += instance.OnSpawn;
            @Spawn.performed += instance.OnSpawn;
            @Spawn.canceled += instance.OnSpawn;
            @Despawn.started += instance.OnDespawn;
            @Despawn.performed += instance.OnDespawn;
            @Despawn.canceled += instance.OnDespawn;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerActsActions" />
        private void UnregisterCallbacks(IPlayerActsActions instance)
        {
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Command.started -= instance.OnCommand;
            @Command.performed -= instance.OnCommand;
            @Command.canceled -= instance.OnCommand;
            @ModifierShift.started -= instance.OnModifierShift;
            @ModifierShift.performed -= instance.OnModifierShift;
            @ModifierShift.canceled -= instance.OnModifierShift;
            @ModifierControl.started -= instance.OnModifierControl;
            @ModifierControl.performed -= instance.OnModifierControl;
            @ModifierControl.canceled -= instance.OnModifierControl;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @NumberKey1.started -= instance.OnNumberKey1;
            @NumberKey1.performed -= instance.OnNumberKey1;
            @NumberKey1.canceled -= instance.OnNumberKey1;
            @NumberKey2.started -= instance.OnNumberKey2;
            @NumberKey2.performed -= instance.OnNumberKey2;
            @NumberKey2.canceled -= instance.OnNumberKey2;
            @NumberKey3.started -= instance.OnNumberKey3;
            @NumberKey3.performed -= instance.OnNumberKey3;
            @NumberKey3.canceled -= instance.OnNumberKey3;
            @NumberKey4.started -= instance.OnNumberKey4;
            @NumberKey4.performed -= instance.OnNumberKey4;
            @NumberKey4.canceled -= instance.OnNumberKey4;
            @NumberKey5.started -= instance.OnNumberKey5;
            @NumberKey5.performed -= instance.OnNumberKey5;
            @NumberKey5.canceled -= instance.OnNumberKey5;
            @NumberKey6.started -= instance.OnNumberKey6;
            @NumberKey6.performed -= instance.OnNumberKey6;
            @NumberKey6.canceled -= instance.OnNumberKey6;
            @NumberKey7.started -= instance.OnNumberKey7;
            @NumberKey7.performed -= instance.OnNumberKey7;
            @NumberKey7.canceled -= instance.OnNumberKey7;
            @NumberKey8.started -= instance.OnNumberKey8;
            @NumberKey8.performed -= instance.OnNumberKey8;
            @NumberKey8.canceled -= instance.OnNumberKey8;
            @NumberKey9.started -= instance.OnNumberKey9;
            @NumberKey9.performed -= instance.OnNumberKey9;
            @NumberKey9.canceled -= instance.OnNumberKey9;
            @CameraMove.started -= instance.OnCameraMove;
            @CameraMove.performed -= instance.OnCameraMove;
            @CameraMove.canceled -= instance.OnCameraMove;
            @CameraRotateToggle.started -= instance.OnCameraRotateToggle;
            @CameraRotateToggle.performed -= instance.OnCameraRotateToggle;
            @CameraRotateToggle.canceled -= instance.OnCameraRotateToggle;
            @ToggleOverviewZoom.started -= instance.OnToggleOverviewZoom;
            @ToggleOverviewZoom.performed -= instance.OnToggleOverviewZoom;
            @ToggleOverviewZoom.canceled -= instance.OnToggleOverviewZoom;
            @CenterOnSelection.started -= instance.OnCenterOnSelection;
            @CenterOnSelection.performed -= instance.OnCenterOnSelection;
            @CenterOnSelection.canceled -= instance.OnCenterOnSelection;
            @ToggleFollowSelection.started -= instance.OnToggleFollowSelection;
            @ToggleFollowSelection.performed -= instance.OnToggleFollowSelection;
            @ToggleFollowSelection.canceled -= instance.OnToggleFollowSelection;
            @GoHome.started -= instance.OnGoHome;
            @GoHome.performed -= instance.OnGoHome;
            @GoHome.canceled -= instance.OnGoHome;
            @CameraZoomScroll.started -= instance.OnCameraZoomScroll;
            @CameraZoomScroll.performed -= instance.OnCameraZoomScroll;
            @CameraZoomScroll.canceled -= instance.OnCameraZoomScroll;
            @Spawn.started -= instance.OnSpawn;
            @Spawn.performed -= instance.OnSpawn;
            @Spawn.canceled -= instance.OnSpawn;
            @Despawn.started -= instance.OnDespawn;
            @Despawn.performed -= instance.OnDespawn;
            @Despawn.canceled -= instance.OnDespawn;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActsActions.UnregisterCallbacks(IPlayerActsActions)" />.
        /// </summary>
        /// <seealso cref="PlayerActsActions.UnregisterCallbacks(IPlayerActsActions)" />
        public void RemoveCallbacks(IPlayerActsActions instance)
        {
            if (m_Wrapper.m_PlayerActsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerActsActions.AddCallbacks(IPlayerActsActions)" />
        /// <seealso cref="PlayerActsActions.RemoveCallbacks(IPlayerActsActions)" />
        /// <seealso cref="PlayerActsActions.UnregisterCallbacks(IPlayerActsActions)" />
        public void SetCallbacks(IPlayerActsActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerActsActions" /> instance referencing this action map.
    /// </summary>
    public PlayerActsActions @PlayerActs => new PlayerActsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerActs" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerActsActions.AddCallbacks(IPlayerActsActions)" />
    /// <seealso cref="PlayerActsActions.RemoveCallbacks(IPlayerActsActions)" />
    public interface IPlayerActsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Select" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelect(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Command" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCommand(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ModifierShift" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnModifierShift(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ModifierControl" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnModifierControl(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MousePosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMousePosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NumberKey1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNumberKey1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NumberKey2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNumberKey2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NumberKey3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNumberKey3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NumberKey4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNumberKey4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NumberKey5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNumberKey5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NumberKey6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNumberKey6(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NumberKey7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNumberKey7(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NumberKey8" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNumberKey8(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NumberKey9" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNumberKey9(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CameraMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CameraRotateToggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraRotateToggle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ToggleOverviewZoom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleOverviewZoom(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CenterOnSelection" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCenterOnSelection(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ToggleFollowSelection" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleFollowSelection(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GoHome" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGoHome(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CameraZoomScroll" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraZoomScroll(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spawn" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpawn(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Despawn" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDespawn(InputAction.CallbackContext context);
    }
}
